### ISSUE TITLE
Teacher Feedback: Update to datagrid views to only allow an update option when the user has changed a field

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#103]
Edit button on dashboard is confusing. I was expecting dialog to pop up to edit something. If this is for changes made to the budget, maybe name it update and only make button active when the user has change the title. The same applies for the edit button on the other tabs.

**Comment by pdean1** [comment]
@iledelin

**Comment by iledelin** [comment]
if there are no changes the when the user hits the edit button on the datagridview the database is not updated.  The user will receive a message that there were no changes and the item was not updated.

I was unable to deteremine how to disable a button on a datagridview.
