### ISSUE TITLE
Teacher Feedback: Why not have add expense, bill, etc. just be an add button and then it adds a blank row to the gridview that the user can complete?

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#104]
Why not have add earning, expense, bill, etc. just be an add button and then it adds a blank row to the gridview that the user can complete?

**Comment by pdean1** [comment]
@iledelin

**Comment by iledelin** [comment]
add functionality for user to add an expense from the datagridview.
Removed the add fields on the left of the expense form
Need to change button names

**Comment by iledelin** [comment]
Complete functionality to allow users to add an expense from the datagridview
