### ISSUE TITLE
As a developer I would like an, Entity Relationship Diagram of our database so that I can see the relations between tables visually

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#11]

**Comment by pdean1** [comment]
[Database_ERD.zip](https://github.com/pdean1/CS6920-Group-4-Project/files/315288/Database_ERD.zip)
ERD Diagram from Design 1

**Comment by pdean1** [comment]
![workbench_erd](https://cloud.githubusercontent.com/assets/16711839/16096135/a188c012-3315-11e6-83b3-c1e816920c3a.PNG)
Based on Issue #5 and #2

**Comment by twilli58** [comment]
Looks really good! Do we want just email address for sign up or full names for the database?
