### ISSUE TITLE
As a developer, I want to develop story boards to get a sense of how the website will look, feel and behave.

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#13]

**Comment by iledelin** [comment]
Draft of storyboards

[BudgetBuddyStoryBoard.pdf](https://github.com/pdean1/CS6920-Group-4-Project/files/321414/BudgetBuddyStoryBoard.pdf)

**Comment by iledelin** [comment]
update to the storyboard, added more pages and details.  2nd draft
Add email address to the new user page, remove the recurring field and add more pages to show the flow of the application

[BudgetBuddyStoryBoard1.pdf](https://github.com/pdean1/CS6920-Group-4-Project/files/321598/BudgetBuddyStoryBoard1.pdf)
Visio does not allow multiple pages to be saved as .png, .gif, or, jpeg

**Comment by iledelin** [comment]
update storyboard with more details.  3rd draft
Add panel to Main page and tip of the day and activities
And figured out how to get the pages as .jpg

![file-page1](https://cloud.githubusercontent.com/assets/19809080/16171279/c00f84c4-3538-11e6-9ca0-1022f42a06ec.jpg)
![file-page2](https://cloud.githubusercontent.com/assets/19809080/16171278/bfbcee08-3538-11e6-8a9c-dfaa615e3789.jpg)
![file-page3](https://cloud.githubusercontent.com/assets/19809080/16171273/bfb96684-3538-11e6-87ce-b4a8ba3559ed.jpg)
![file-page4](https://cloud.githubusercontent.com/assets/19809080/16171275/bfbb96fc-3538-11e6-89d3-95cd1549e6aa.jpg)
![file-page5](https://cloud.githubusercontent.com/assets/19809080/16171277/bfbc00ce-3538-11e6-9e22-242c9c4b96d2.jpg)
![file-page6](https://cloud.githubusercontent.com/assets/19809080/16171274/bfbb304a-3538-11e6-9a8a-ae576db8ee4f.jpg)

**Comment by iledelin** [comment]
Create a storyboard for the reporting page

![page7reports](https://cloud.githubusercontent.com/assets/19809080/16177426/eb89476c-35fa-11e6-92d0-94c056ec239b.png)
