### ISSUE TITLE
As a developer, I want to have an initial database design to store the data.

### ISSUE THREAD

**Issue by iledelin** [pdean1/CS6920-Group-4-Project#2]
## Initial Design
- Database Schema

**Comment by pdean1** [comment]
Here is the initial design
[Design_1.zip](https://github.com/pdean1/CS6920-Group-4-Project/files/315238/Design_1.zip)

**Comment by pdean1** [comment]
Here is design Number 2, We need to figure out what to take out/add.
[Design_2.zip](https://github.com/pdean1/CS6920-Group-4-Project/files/316152/Design_2.zip)

**Comment by pdean1** [comment]
Here is design number 3
![database_erd_3](https://cloud.githubusercontent.com/assets/16711839/16092012/2355c034-3304-11e6-9e94-dd24dadab4bc.PNG)
![database_schema](https://cloud.githubusercontent.com/assets/16711839/16092011/2354c2d8-3304-11e6-8a96-c5ee4533702e.PNG)

**Comment by pdean1** [comment]
I believe the designs are ready to be reviewed, I am personally a fan of [Number 3](https://cloud.githubusercontent.com/assets/16711839/16092011/2354c2d8-3304-11e6-8a96-c5ee4533702e.PNG)

**Comment by twilli58** [comment]
Hi Patrick,

Based on the feedback from the teacher and the fact that we need to title
our application. I am thinking that it may be in our best interest to start
from scratch in the github. What do you guys think.

**Comment by pdean1** [comment]
I do not believe that that would be a good idea, we'd have to redistribute access, move code, issues, and wiki.

I think we should just fix the problems present in the repository/wiki/issues.

**Comment by twilli58** [comment]
okay, I am going to work on the wiki now and we can meet later today if
everyone is available

**Comment by pdean1** [comment]
![database_erd](https://cloud.githubusercontent.com/assets/16711839/16095071/084cabba-3311-11e6-94c3-a8f561ca86c6.PNG)
![database_schema](https://cloud.githubusercontent.com/assets/16711839/16095072/0858bb4e-3311-11e6-8e78-a815f17e30e4.PNG)
Pending any concerns, this is the final design for the database.

**Comment by twilli58** [comment]
I agree number 3 looks like it would best fit into our project and covers the most.

**Comment by iledelin** [comment]
I like number 3 as well.  I do beleive we need to have the users First and Lastname.  This can be used when they sign in, "Welcome Ivy" looks better than "Welcome iedelin1 or iedelin1@my.westga.edu".  The first and last name columns should be added to the User table.
