### ISSUE TITLE
As a developer, I want to have mock-up designs of the screens we are to create as a visual reference.

### ISSUE THREAD

**Issue by twilli58** [pdean1/CS6920-Group-4-Project#27]
Create basic look and feel of applications UI. Approximate range 2 days. Started mock-up prior to creation of issue.

**Comment by twilli58** [comment]
[BudgetMockups.pdf](https://github.com/pdean1/CS6920-Group-4-Project/files/317726/BudgetMockups.pdf)
Basic beginning mock up for our application

**Comment by pdean1** [comment]
I **love** these mockups, I am interested in seeing how this will work!

**Comment by twilli58** [comment]
me too. lol

**Comment by twilli58** [comment]
Range completed in 1 days 13 hours
