### ISSUE TITLE
As a developer, I want to create initial wireframe diagrams to plan the application layout.

### ISSUE THREAD

**Issue by iledelin** [pdean1/CS6920-Group-4-Project#3]
Approximate estimate range 6 hours

**Comment by twilli58** [comment]
Here is our initial wireframe with storyboard utilization. It is our first draft. We need to finalize it. 
[WireFrames_Storyboard_FirstDraft.pdf](https://github.com/pdean1/CS6920-Group-4-Project/files/319376/WireFrames_Storyboard_FirstDraft.pdf)

Actual range 5.25 hours

**Comment by pdean1** [comment]
Interesting design I like it
