### ISSUE TITLE
As a developer I'd like to have model classes, based on the table so that I may use them as objects when I am coding

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#6]
This requires using the Database created in issues #2 #5

**Comment by pdean1** [comment]
[Model Classes](https://github.com/pdean1/CS6920-Group-4-Project/tree/master/CS6920Group4Project/model/db_tables) that resemble tables in the database

references issues #2 #5

**Comment by twilli58** [comment]
I hope you don't mind but I re-structured the project files to better fit the MVC model that we usually use in this type of project.
