### ISSUE TITLE
As a developer, I want to allow the user to be able to tab to the next textbox for easy use.

### ISSUE THREAD

**Issue by iledelin** [pdean1/CS6920-Group-4-Project#61]

**Comment by pdean1** [comment]
Estimated time 2 hours

**Comment by pdean1** [comment]
https://github.com/pdean1/CS6920-Group-4-Project/commit/4416c950cceaa727fb88cec2081e012966204e8b

**Comment by pdean1** [comment]
Reopening issue to take care of tab issues in ManageEarnings.cs and ManageExpenses.cs

**Comment by pdean1** [comment]
392bcaedd6c25ce0ac69ab75888153fc5a95f73d

**Comment by pdean1** [comment]
9e122be1ffac4014f85c013bfc7d2f86930480b9
