### ISSUE TITLE
As a developer, I want to create a theme for the application to define the look of the pages and controls.

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#8]

**Comment by twilli58** [comment]
![budgetlogo](https://cloud.githubusercontent.com/assets/16619498/16106204/7d3392b4-3360-11e6-96dd-662513ad237f.png)
Decided to go with a basic finance theme using general finance tools such as calculator, spreedsheets and accounting tools to design pages.
