### ISSUE TITLE
Bug Fix: Unhandled exception in ManageEarnings.cs

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#87]
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706397/9f04561a-4578-11e6-977e-70a8b2d59bb8.PNG)
This bug contains many steps to recreate.
1. Attempt to add an earning: 
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706402/ef6b4c9e-4578-11e6-9070-53baf6fc3e7d.PNG)
2. Notice that there is now an additional delete column added to the earning table: 
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706411/2a6d0404-4579-11e6-8da2-c95862c0a23a.PNG)
3. Now go and delete an earning you should receive a unhandled number format  exception: 
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706418/6799f26a-4579-11e6-8d39-a5599ff9473b.PNG)

**Comment by pdean1** [comment]
Correction issue was fixed, input was incorrect reserving this issue for a later time. Sorry for the confusion...

**Comment by pdean1** [comment]
@twilli58

**Comment by pdean1** [comment]
Found the cause of the issue: 
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706655/83a9d156-4582-11e6-9420-9148369b33f1.PNG)
This is causing EDIT to appear as the value of the record ID. The problem code is when this function:
     populateGridView()
is called

```
    public void populateGridView()
    {
        // ... some code....
            DataGridViewButtonColumn editbut = new DataGridViewButtonColumn();
            editbut.Text = "EDIT";
            editbut.Name = "EDIT";
            editbut.HeaderText = "";
            editbut.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
            editbut.UseColumnTextForButtonValue = true;
            editbut.DefaultCellStyle.ForeColor = Color.White;
            earnGridView.Columns.Add(editbut);

            //add new button column to the DataGridView
            //This column displays a delete Button in each row
            DataGridViewButtonColumn delbut = new DataGridViewButtonColumn();
            delbut.Text = "DELETE";
            delbut.Name = "DELETE";
            delbut.AutoSizeMode = DataGridViewAutoSizeColumnMode.AllCells;
            delbut.UseColumnTextForButtonValue = true;
            delbut.DefaultCellStyle.BackColor = Color.White;
            earnGridView.Columns.Add(delbut);
        // More code
    }
```

It re-adds the buttons to the view, producing duplicates.

**Comment by pdean1** [comment]
@twilli58 Updated the description of the issue. I recommend you take a look rather than me... My solution would be to chop up the binding source and take a different approach...

**Comment by pdean1** [comment]
This problem has re-manifested it self in the inability to delete earnings from the program.

**Comment by iledelin** [comment]
I fixed this issue problem and I was working on fixing the delete issue that I caused.  I uploaded the code so that if anyone was making changes I didn't want to lose my code.
