### ISSUE TITLE
Bug fix: Unhandled format exception from ManageExpense.cs This problem is just like issue #87

### ISSUE THREAD

**Issue by pdean1** [pdean1/CS6920-Group-4-Project#88]
Refer to #87 The problem in ManageExpense.cs is just like the one in ManageEarnings.cs

@twilli58 
![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706438/861e8560-457a-11e6-8054-5ded8d69460a.PNG)

![bugfix](https://cloud.githubusercontent.com/assets/16711839/16706439/94acea86-457a-11e6-8fb3-6a8c952979ba.PNG)

**Comment by iledelin** [comment]
I wasn't able to recreate the addition delete column but I did fix the Unhandled format exception by adding a try catch and checking to see if the recid is null or empty.

**Comment by iledelin** [comment]
I was able to recreate the issue to prevent multiple add and delete buttons on the datagridview and the reorder of the columns by not rebuilding the column when adding or deleting a record.
