### ISSUE TITLE
As a user I'd like the date fields in the data grids to be datetime columns so that I can easily put in new values.

### ISSUE THREAD

**Issue by iledelin** [pdean1/CS6920-Group-4-Project#98]
Provide error and format checking

**Comment by pdean1** [comment]
@iledelin

**Comment by iledelin** [comment]
upload some code to add the datetimepicker to the datagridview on the expense form.  I've run into an issue and have asked for help and will look more into it later.  Committed the code for help and not to lose any work incase others are working.

**Comment by iledelin** [comment]
I fixed the issues I was having with the dateTimePicker.  I have a 2nd reference and removed it.  I also fixed the date display issue by setting the custom option
